# Generated by Django 3.1 on 2020-08-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=False, verbose_name='correct'),
        ),
    ]
